In [1]:
import numpy as np

In [4]:
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
y = [1,2,3,4]
print(y)
print(type(x))

[1, 2, 3, 4]
<class 'numpy.ndarray'>


In [6]:
x = [1,2,3,4]
y = np.array([1,23,4])

print(y)
print(type(y))

[ 1 23  4]
<class 'numpy.ndarray'>


In [9]:
lst=[1,2,3,4]
arr=np.array(lst)

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr.shape

(4,)

In [16]:
arr1=np.array([[1,2,3],[4,5,6]])

In [18]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
## 2 dimension
arr1.shape

(2, 3)

In [19]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
1+1

2

In [23]:
lst=[1,2,3,4]
arr=np.array(lst)

In [24]:
arr

array([1, 2, 3, 4])

In [25]:
type(arr)

numpy.ndarray

In [26]:
arr.shape

(4,)

In [32]:
arr1=np.array([[1,2,3],[4,5,6]])

In [33]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
## 2 diamension
arr1.shape

(2, 3)

In [36]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [37]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [38]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [39]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr1.dtype

dtype('int32')

In [45]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [48]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [50]:
list(range(1,20,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [51]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [52]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [55]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [57]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [61]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [64]:
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [67]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [68]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
print("Random number generation(uniform distribution)")
np.random.rand(2,3)

Random number generation(uniform distribution)


array([[0.1048836 , 0.73402949, 0.2160058 ],
       [0.36288351, 0.37902424, 0.66462309]])

In [70]:
print("Random number following a normal distribution with mean=0 and std=1")
print(np.random.randn(5,3))

Random number following a normal distribution with mean=0 and std=1
[[ 0.53662926  0.3486      0.8565869 ]
 [ 1.53243257  0.75573967 -0.6877994 ]
 [ 0.26563088  0.54585717  0.41768585]
 [-1.34588187  0.44942179  0.20027279]
 [-0.32468087 -0.56678316  0.89781717]]


In [74]:
np.random.randint(1,100,50)

array([49, 68, 90, 57, 82, 73, 65,  7, 12, 61, 18, 99, 43,  7, 52, 84,  4,
       67,  8, 99, 92, 14, 12, 85, 43,  8, 48, 44,  7,  3, 53, 15, 78, 86,
       21, 68, 65, 94, 82, 73, 25, 94, 32, 90, 77, 52, 87, 60, 58, 30])

In [75]:
np.random.randint(1,100,(4,4))

array([[40, 64, 12, 50],
       [32, 46, 41, 92],
       [27,  7, 33,  2],
       [56, 86, 93, 77]])

In [76]:
arr=np.arange(0,11)

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
## slicing
arr[2:7:3]

array([2, 5])

In [88]:
arr[-1:7:-1]

array([10,  9,  8])

In [93]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [95]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [96]:
arr1

array([[63, 51,  6, 72],
       [82, 96, 46, 53],
       [50, 83, 99, 15],
       [42, 87, 41, 42],
       [86, 60, 68, 43]])

In [102]:
arr1[2:4,1:3]

array([[83, 99],
       [87, 41]])

In [100]:
arr1[3:,1:]

array([[87, 41, 42],
       [60, 68, 43]])

In [99]:
arr1[0:3,0:3]

array([[63, 51,  6],
       [82, 96, 46],
       [50, 83, 99]])

In [106]:
arr1[-3:-1,-3:-1]

array([[83, 99],
       [87, 41]])

In [108]:
## universal functions

arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [109]:
arr1

array([[28, 12, 76],
       [61, 77,  6],
       [40, 19, 92]])

In [110]:
arr2

array([[30, 94, 47],
       [92, 91, 46],
       [63, 87, 50]])

In [111]:
arr1 + arr2

array([[ 58, 106, 123],
       [153, 168,  52],
       [103, 106, 142]])

In [112]:
arr1 * arr2

array([[ 840, 1128, 3572],
       [5612, 7007,  276],
       [2520, 1653, 4600]])

In [113]:
arr1 / arr2

array([[0.93333333, 0.12765957, 1.61702128],
       [0.66304348, 0.84615385, 0.13043478],
       [0.63492063, 0.2183908 , 1.84      ]])

In [114]:
np.sqrt(arr1)

array([[5.29150262, 3.46410162, 8.71779789],
       [7.81024968, 8.77496439, 2.44948974],
       [6.32455532, 4.35889894, 9.59166305]])

In [115]:
np.exp(arr2)

array([[1.06864746e+13, 6.66317622e+40, 2.58131289e+20],
       [9.01762841e+39, 3.31740010e+39, 9.49611942e+19],
       [2.29378316e+27, 6.07603023e+37, 5.18470553e+21]])

In [116]:
np.log10(arr1)

array([[1.44715803, 1.07918125, 1.88081359],
       [1.78532984, 1.88649073, 0.77815125],
       [1.60205999, 1.2787536 , 1.96378783]])

In [117]:
arr1=np.arange(1,10)

In [119]:
arr1[2:]=1000

In [120]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [126]:
np.dot(arr1,arr2)

ValueError: shapes (9,) and (3,3) not aligned: 9 (dim 0) != 3 (dim 0)

In [124]:
np.matmul(arr1,arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 9)